### ISSUE TITLE
How set PrefetchCount ?

### ISSUE THREAD

**Issue by artemkrotov** [freenowtech/spring-multirabbit#19]
Hi! 

I have a question, how set prefetch count in rabbit mq with your library? 

**Standard case with Springboot Amqp:**

` @Bean
    public RabbitListenerContainerFactory<SimpleMessageListenerContainer> prefetchRabbitListenerContainerFactory(
            ConnectionFactory rabbitConnectionFactory, @Value("${mcat.async.prefetch-count:10}") Integer prefetchCount) {
        SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
        factory.setConnectionFactory(rabbitConnectionFactory);
        factory.setPrefetchCount(prefetchCount);
        factory.setDefaultRequeueRejected(false);
        factory.setErrorHandler(new CustomConditionalRejectingErrorHandler());
        return factory;
    }`

**Listener**
`
@RabbitListener(queues = "${mcat.async.data.internal.from.prodcat.to.premodereation.hierarchy.enabled:sp.to.prodcat.hierarchy.queue}",
            containerFactory = "prefetchRabbitListenerContainerFactory")
    @Override
    public void process(HierarchyToPremoderationMessage message) throws Exception {
        super.process(message);
    }
`

**So, If I add lib, I have some error:**

Description:

A component required a bean named 'prefetchRabbitListenerContainerFactory-admin' that could not be   ##found.
Action
Consider defining a bean named 'prefetchRabbitListenerContainerFactory-admin' in your configuration.

**Comment by rwanderc** [comment]
Hi @artemkrotov, thank you for your message.
The reason that happens is that SpringMultirabbit (to offer the functionality of allowing multiple brokers) needs to orchestrate the instantiation of ContainerFactories, RabbitAdmins, etc.
As you instantiate a ContainerFactory manually, this bean is tried to be processed by Multirabbit and does not find the relative RabbitAdmin.

What you can do is to provide this prefetchCount via configuration (for `spring.rabbitmq` or `spring.multirabbitmq`) and provide an ErrorHandler bean like:

```
@Bean
public ErrorHandler errorHandler() {
    return new ConditionalRejectingErrorHandler(customExceptionStrategy());
}
```


This happens because the integration of Multirabbit with SpringAmqp is not intrusive. It respects SpringAmqp's implementation, and then do not have full visibility of the beans created out of a Listener processed. However, this [PR](https://github.com/spring-projects/spring-amqp/pull/1111) is to contribute Multirabbit to SpringAmqp and I hope it fixes issues like this. Keep posted.
